name: MLFlow CI-CD-Hello

on:
  [workflow_dispatch]
jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Training script
        run: |
          python src/train.py
  serving:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Serving API
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Training script
        run: |
          python src/train.py